name: build

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  build:
    name: Build Wheel
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Build Wheel
        run: |
          python -m pip install setuptools wheel
          python setup.py bdist_wheel
      - name: Archive pyqtgraph wheel
        uses: actions/upload-artifact@v2
        with:
          name: wheel
          path: |
            dist

# - stage: build
#   dependsOn: []
#   jobs:
#   - job: "build_wheel"
#     pool:
#       vmImage: 'Ubuntu 18.04'
#     steps:
#     - task: UsePythonVersion@0
#       inputs:
#         versionSpec: 3.8
#     - script: |
#         python -m pip install setuptools wheel
#         python setup.py bdist_wheel --universal
#       displayName: "Build Python Wheel"
#       continueOnError: false
#     - publish: dist
#       artifact: wheel